server:
  port: 8080

database:
  host: "localhost"
  port: 5432
  user: "admin"
  password: "password"
  name: "employee_db"
  
messageQueue:
  type: "kafka"
  brokers:
    - "kafka:9092"
  url: "http://35.229.242.253:8080/api/clock/"

