version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: native-cloud-hr
    ports:
      - "8080:8080"
    volumes:
      - ./config/.env:/app/config/.env
      - ./config/config.yaml:/app/config/config.yaml