name: Build and Deploy Docker Image to GCP

on:
  push:
    tags:
      - 'v*'  # 例如 v1.0.0、v1.1.3 等版本

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract tag name
      id: extract_tag
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    
    - name: Free up space on GitHub runner
      run: |
        echo "Before cleanup:"
        df -h

        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo apt clean

        echo "After cleanup:"
        df -h
  

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          yibchen/native-cloud-hr:${{ env.TAG }}
          yibchen/native-cloud-hr:latest

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.GCP_SSH_KEY }}

    - name: SSH to GCP VM and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${USER}@${HOST} << EOF
          cd /opt/shared/NativeCloud_HR
          git pull
          sudo docker-compose pull
          sudo docker-compose up -d --build
        EOF
      env:
        USER: ${{ secrets.GCP_SSH_USER }}
        HOST: ${{ secrets.GCP_VM_IP }}
